Repository Diderot-sielinou/Alimana, pull requests merged in 2025-08, with the labels that each got.

#46 Feat/update code
  package-lock.json
  src/app/dashboard/analytics/page.tsx
  src/app/dashboard/inventory/page.tsx
  src/app/dashboard/overview/page.tsx
  src/app/dashboard/page.tsx
  src/app/dashboard/product/page.tsx
  src/app/dashboard/products/new/page.tsx
  src/app/dashboard/products/page.tsx
  src/app/dashboard/settings/page.tsx
  src/app/layout.tsx
  src/components/dashboard/HeaderDasboard.tsx
  src/components/sales/Cart.tsx
  src/components/sales/CategoryFilter.tsx
  src/components/sales/ProductCard.tsx
  src/components/sales/SearchBar.tsx
  src/components/sidebar.tsx
  src/constants/sidebarLinks.js
Labels: ui-ux-improvement, component-architecture, responsive-design

#56 made a fix on the sidebarLinks to seperate the roles from cash regist…
  src/constants/sidebarLinks.js
Labels: ui-ux-improvement

#60 Feat/change language
  INVITATION_FRONTEND_IMPLEMENTATION_PLAN.md
  src/app/acepte-invitation/page.tsx
  src/app/dashboard/analytics/page.tsx
  src/app/dashboard/categories/page.tsx
  src/app/dashboard/invitation/page.tsx
  src/app/dashboard/login/page.tsx
  src/app/dashboard/post/page.tsx
  src/app/dashboard/product/page.tsx
  src/app/dashboard/user-management/page.tsx
  src/app/invite/[token]/page.tsx
  src/components/dashboard/DashboardRedirector.tsx
  src/components/dashboard/HeaderDasboard.tsx
  src/components/dashboard/LoadingSpinner.tsx
  src/components/newComponent/Header.tsx
  src/components/newComponent/common/ProductForm.tsx
  src/components/newComponent/dashbordLayout.tsx
  src/components/newComponent/pos/DataTable.tsx
  src/components/newComponent/products/ProductForm.tsx
  src/components/sales/Cart.tsx
  src/components/sales/CategoryFilter.tsx
  src/components/sales/ProductCard.tsx
  src/components/sales/SearchBar.tsx
  src/constants/sidebarLinks.js
  src/context/DataContext.tsx
  src/context/auth-context.tsx
  src/context/shopContext.tsx
  src/context/store-context.tsx
  src/hooks/useInvitations.ts
  src/hooks/useRoles.ts
  src/services/invitationService.ts
  src/services/roleService.ts
  src/types/invitation.interface.ts
  src/types/user.interface.ts
  src/utils/invitationUtils.ts
Labels: ui-ux-improvement, accessibility-enhancement

#63 add profile page and modifie session page
  next.config.ts
  src/app/dashboard/cash-registers/page.tsx
  src/app/dashboard/product/page.tsx
  src/app/dashboard/profile/page.tsx
  src/components/dashboard/HeaderDasboard.tsx
  src/components/newComponent/ImageUploadField.tsx
  src/components/newComponent/common/ProductForm.tsx
  src/components/sidebar.tsx
  src/constants/sidebarLinks.js
  src/context/auth-context.tsx
  src/context/store-context.tsx
  src/services/utils.ts
  src/types/store.interface.ts
Labels: ui-ux-improvement, component-architecture, responsive-design

#64 remove darkmode implementation
  src/components/dashboard/HeaderDasboard.tsx
Labels: ui-ux-improvement

#65 Feat/roles filter
  src/app/dashboard/roles/page.tsx
  src/components/roles/RoleFilterBar.tsx
Labels: ui-ux-improvement, component-architecture

#67 Feature/upload logo
  next.config.ts
  src/app/create-store/page.tsx
  src/app/dashboard/cash-registers/page.tsx
  src/app/dashboard/post/page.tsx
  src/app/dashboard/product/page.tsx
  src/app/dashboard/profile/page.tsx
  src/components/dashboard/HeaderDasboard.tsx
  src/components/newComponent/ImageUploadField.tsx
  src/components/newComponent/pos/Cart.tsx
  src/components/steps/Step1StoreInfo.tsx
  src/context/auth-context.tsx
  src/context/store-context.tsx
  src/types/user.interface.ts
Labels: ui-ux-improvement, component-architecture, responsive-design
